@Fagdag.Presentation_HostAddress = http://localhost:5247

POST {{Fagdag.Presentation_HostAddress}}/todos
Content-Type: application/json

{
"title": "Foo"
}

###

GET {{Fagdag.Presentation_HostAddress}}/todos/
Accept: application/json

###
